const express = require('express')
const router = express.Router()
const controllers = require('../controllers/index')
const longoControllers = require('../controllers/longoControllers')

router.get('/fish', controllers.getAllFish)
router.get('/fish/:name', controllers.getFishByName)
router.get('/vegetable', controllers.getAllVegetable)
router.get('/vegetable/:name', controllers.getVegetableByName)
router.get('/cereal', controllers.getAllCereal)
router.get('/cereal/:name', controllers.getCerealByName)
router.get('/egg', controllers.getAllEgg)
router.get('/egg/:name', controllers.getEggByName)
router.get('/fat', controllers.getAllFat)
router.get('/fat/:name', controllers.getFatByName)
router.get('/fishAG', controllers.getAllFishAG)
router.get('/fishAG/:name', controllers.getFishAGByName)
router.get('/meat', controllers.getAllMeat)
router.get('/meat/:name', controllers.getMeatByName)
router.get('/meatAG', controllers.getAllMeatAG)
router.get('/meatAG/:name', controllers.getMeatAGByName)
router.get('/fruit', controllers.getAllFruit)
router.get('/fruit/:name', controllers.getFruitByName)
router.get('/milk', controllers.getAllMilk)
router.get('/milk/:name', controllers.getMilkByName)
router.get('/misc', controllers.getAllMisc)
router.get('/misc/:name', controllers.getMiscByName)
router.get('/prodAZ', controllers.getAllProdAZ)
router.get('/prodAZ/:name', controllers.getProdAZByName)

router.get('/longo/cereal', longoControllers.getAllCereal)
router.get('/longo/cereal/:name', longoControllers.getCerealByName)
router.get('/longo/egg', longoControllers.getAllEgg)
router.get('/longo/egg/:name', longoControllers.getEggByName)
router.get('/longo/fat', longoControllers.getAllFat)
router.get('/longo/fat/:name', longoControllers.getFatByName)
router.get('/longo/fruit', longoControllers.getAllFruit)
router.get('/longo/fruit/:name', longoControllers.getFruitByName)
router.get('/longo/meat', longoControllers.getAllMeat)
router.get('/longo/meat/:name', longoControllers.getMeatByName)
router.get('/longo/milk', longoControllers.getAllMilk)
router.get('/longo/milk/:name', longoControllers.getMilkByName)
router.get('/longo/misc', longoControllers.getAllMisc)
router.get('/longo/misc/:name', longoControllers.getMiscByName)
router.get('/longo/vegetable', longoControllers.getAllVegetable)
router.get('/longo/vegetable/:name', longoControllers.getVegetableByName)

module.exports = router
