const express = require('express')
const router = express.Router()
const controllers = require('../controllers')
router.get('/fish', controllers.getAllFish)
router.get('/fish/:name', controllers.getFishByName)
router.get('/vegetable', controllers.getAllVegetable)
router.get('/vegetable/:name', controllers.getVegetableByName)
router.get('/cereal', controllers.getAllCereal)
router.get('/cereal/:name', controllers.getCerealByName)
router.get('/egg', controllers.getAllEgg)
router.get('/egg/:name', controllers.getEggByName)
router.get('/fat', controllers.getAllFat)
router.get('/fat/:name', controllers.getFatByName)
router.get('/fishAG', controllers.getAllFishAG)
router.get('/fishAG/:name', controllers.getFishAGByName)
router.get('/meat', controllers.getAllMeat)
router.get('/meat/:name', controllers.getMeatByName)
router.get('/meatAG', controllers.getAllMeatAG)
router.get('/meatAG/:name', controllers.getMeatAGByName)
router.get('/fruit', controllers.getAllFruit)
router.get('/fruit/:name', controllers.getFruitByName)
router.get('/milk', controllers.getAllMilk)
router.get('/milk/:name', controllers.getMilkByName)
router.get('/misc', controllers.getAllMisc)
router.get('/misc/:name', controllers.getMiscByName)
router.get('/prodAZ', controllers.getAllProdAZ)
router.get('/prodAZ/:name', controllers.getProdAZByName)

module.exports = router
